# Generated by Django 5.0 on 2023-12-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
