# Generated by Django 5.0 on 2023-12-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
