# Generated by Django 5.0 on 2023-12-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cuenta',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
