# Generated by Django 5.0 on 2023-12-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_usuario_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cuenta',
            field=models.CharField(choices=[('SCG', 'SCG'), ('BETDSI', 'BETDSI'), ('INS', 'INS')], max_length=150, null=True),
        ),
    ]
