# Generated by Django 5.0 on 2023-12-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_cuenta_alter_usuario_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cuenta',
        ),
    ]
