# Generated by Django 5.0 on 2023-12-26 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_usuario_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='user.cuenta'),
        ),
    ]
