# Generated by Django 5.0 on 2024-01-04 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_usuario_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reporte', models.IntegerField()),
                ('fecha_reporte', models.DateField(auto_now=True)),
                ('tipo_reporte', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('cuenta_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_reportes', to='user.cuenta')),
            ],
        ),
    ]
