# Generated by Django 5.0 on 2024-01-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='id_reporte',
            field=models.IntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_usuarios', to='user.cuenta'),
        ),
    ]
