# Generated by Django 5.0 on 2024-01-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_reporte_id_reporte_alter_usuario_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='source',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
