# Generated by Django 5.0 on 2024-01-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_reporte_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='source',
            field=models.CharField(max_length=150),
        ),
    ]
