# Generated by Django 5.0 on 2024-01-08 22:57

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_reporte_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='source',
            field=models.FileField(null=True, upload_to=user.models.generate_nessus_filename),
        ),
    ]
