# Generated by Django 5.0 on 2024-01-11 22:45

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_reporte_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='file_report',
            field=models.FileField(null=True, upload_to=user.models.generate_dradis_filename),
        ),
    ]
