# Generated by Django 5.0 on 2024-02-09 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_reporte_file_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tarea', models.IntegerField(editable=False, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('incidente', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Not Started', 'Not Started')], max_length=100)),
                ('loe', models.CharField(max_length=100)),
                ('cuenta_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_tareas', to='user.cuenta')),
            ],
        ),
    ]
