# Generated by Django 5.0 on 2024-02-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_tarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='cuenta_reporte',
            new_name='cuenta_tarea',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='loe',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
