# Generated by Django 5.0 on 2024-02-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_rename_cuenta_reporte_tarea_cuenta_tarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='loe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
