# Generated by Django 5.0 on 2024-02-20 17:28

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_tarea_descripcion_alter_tarea_loe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='file_report',
            field=models.FileField(blank=True, null=True, upload_to=user.models.generate_dradis_filename),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='source',
            field=models.FileField(blank=True, null=True, upload_to=user.models.generate_nessus_filename),
        ),
    ]
