# Generated by Django 5.0 on 2024-02-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_usuario_nombre_usuario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
    ]
