# Generated by Django 5.0 on 2024-02-28 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_usuario_nombre_usuario_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contrato', models.IntegerField(editable=False, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=100)),
                ('cuenta_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_contratos', to='user.cuenta')),
            ],
        ),
    ]
