# Generated by Django 5.0 on 2024-02-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_usuario_nombre_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='id_cuenta',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
