# Generated by Django 5.0 on 2024-02-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_cuenta_id_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='id_cuenta',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
