# Generated by Django 5.0 on 2024-02-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_cuenta_id_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='severity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
