# Generated by Django 5.0 on 2024-02-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_tarea_fecha_tarea_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='severity',
            field=models.CharField(max_length=100),
        ),
    ]
