# Generated by Django 5.0 on 2024-03-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_alter_tarea_fecha_alter_tarea_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='severity',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100),
        ),
    ]
