# Generated by Django 5.0 on 2024-03-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_alter_tarea_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='id_contrato',
            field=models.CharField(max_length=100),
        ),
    ]
