# Generated by Django 5.0 on 2024-03-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_alter_contrato_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=100),
        ),
    ]
