# Generated by Django 5.0 on 2024-03-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_alter_contrato_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='id_contrato',
            field=models.IntegerField(),
        ),
    ]
