# Generated by Django 5.0 on 2024-03-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_alter_contrato_id_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], max_length=100, null=True),
        ),
    ]
