# Generated by Django 5.0 on 2024-03-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_alter_usuario_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='target',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
