# Generated by Django 5.0 on 2024-03-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_alter_reporte_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='loe',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
