# Generated by Django 5.0 on 2024-03-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_alter_tarea_loe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='loe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
