# Generated by Django 5.0 on 2024-03-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_alter_tarea_loe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarea',
            name='loe',
            field=models.FloatField(max_length=100),
        ),
    ]
