# Generated by Django 5.0 on 2024-03-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_remove_usuario_id_usuario_user_id_alter_tarea_loe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
