# Generated by Django 5.0 on 2024-03-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_remove_usuario_user_id_usuario_id'),
    ]
