# Generated by Django 5.0 on 2024-03-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_remove_usuario_id_usuario_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
