# Generated by Django 5.0 on 2024-04-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0058_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
