# Generated by Django 5.0 on 2024-04-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0059_comment_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
    ]
