# Generated by Django 5.0 on 2024-04-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_tarea_fecha_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='asignee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
