# Generated by Django 5.0 on 2024-05-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_alter_comment_fecha_alter_reporte_fecha_reporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
