# Generated by Django 5.0 on 2024-05-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0063_alter_usuario_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
