# Generated by Django 5.0 on 2024-06-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0064_alter_usuario_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
